import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { memo } from 'react'
import { Layout } from '../components/Layout'
import { Main } from '../components/Main'

const Home: NextPage = ({}) => {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="theme-color" content="#d6eef5" />
        {/* meta theme-color para safari */}
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
        <title>Anne&Caio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="casamento, caio, anne, casal, praia, pix, site de casamento, confirme sua presença, Atlantis Buffet" />
        <meta name="author" content="Caio Queiroz e Anne Queiroz" />
        {/* open_graph - facebook */}
        <meta property="og:title" content="anne e caio." />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="O site de casamento da Anne e do Caio é um espaço para compartilhar os detalhes da cerimônia e recpção desse momento tão especial para o casal. Este site foi criado com todo amor e carinho para me amada, Anne." />
        <meta property="og:url" content="https://www.casamentoanneecaio.com" />
        <meta property="og:site_name" content="casamento anne e caio." />
        <meta property="og:image" content="https://next-casamentoecaio.s3.amazonaws.com/image-site/sitemapimagecasamentoanneecaio.png" />
        <meta property="og:image:secure_url" itemProp="image" content="https://next-casamentoecaio.s3.amazonaws.com/image-site/sitemapimagecasamentoanneecaio.png"/>
        <meta property="og:image:alt" content="Site de casamento Anne e Caio" />
        <meta property="og:image:width" content="1256" />
        <meta property="og:image:height" content="815" />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:locale" content="pt_BR" />
        {/* open_graph - facebook */}
        <meta name="twitter:cards" content="sumary" />
        <meta name="twitter:url" content="https://www.casamentoanneecaio.com" />
        <meta name="twitter:title" content="anne e caio." />
        <meta name="twitter:description" content="O site de casamento da Anne e do Caio é um espaço para compartilhar os detalhes da cerimônia e recpção desse momento tão especial para o casal. Este site foi criado com todo amor e carinho para me amada, Anne." />
        <meta name="twitter:url" content="https://www.casamentoanneecaio.com" />
        <meta name="twitter:image" content="https://next-casamentoecaio.s3.amazonaws.com/image-site/sitemapimagecasamentoanneecaio.png" />
        <meta name="twitter:image:width" content="1256" />
        <meta name="twitter:image:height" content="815" /> 
        <meta name="twitter:image:type" content="image/png" />
        <meta name="twitter:site" content="@caiocezardeque1" />
        <meta name="twitter:creator" content="@caiocezardeque1"/>
      </Head>
      <Main>
          <Layout />
      </Main>
    </>
  )
}

export default memo(Home);

export const getStaticProps: GetStaticProps = async () => {
  return { 
    props: {},
    revalidate: 60 * 60 * 24 * 2 //48 horas
   }
}

